### ISSUE TITLE
Create MakeFile for executing unit tests

### ISSUE THREAD

**Issue by AlexanderJDupree** [AlexanderJDupree/LinkedListsCPP#41]
- [x] Write Makefile for quick and easy compilation and running of Unit tests.
- [ ] Update README execute unit tests section on how to build and run the executable using the make file.

Makefile should first pre-compile the tests_main.cpp into an object file and put it in tests/bin directory. Then compile all source files and the test files and link them with the test_main.o resulting in the executable runTests to be stored in tests/debug directory.

**Comment by jake-bickle** [comment]
Any reasons why you want tests_main.cpp put into tests/bin? Why not put its object into a general obj/ along with the rest of the obj files and have it ready to be linked?

**Comment by AlexanderJDupree** [comment]
Yeah, that can work too. Just have the make file make the high level bin directory and store all the object files in there. Just make sure it's on the gitignore so we don't have a bunch of binary files committed to the repo.

**Comment by jake-bickle** [comment]
Well I matched the specifications anyways on PR #46. Check it out when you get the chance!
